config/routes.rb
Blatter::Application.routes.draw do
  resources :blats
  root to: 'blats#index'
end

app/models/blat.rb
class Blat < ActiveRecord::Base
  validates :title, presence: true, length: { maximum: 140 }
  validates :body, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/blats_controller.rb
class BlatsController < ApplicationController
  before_action :find_blat, only: [:show, :edit, :update, :destroy]

  def index
    @blats = if params[:show_all].present?
      Blat.all
    else
      Blat.where('updated_at > ?', 7.days.ago)
    end.order(updated_at: :desc)
  end

  def show
  end

  def new
    @blat = Blat.new
  end

  def create
    @blat = Blat.new(blat_params)

    if @blat.save
      # Using flash[] because we want it to appear on the *next* request
      flash[:notice] = 'Created a new blat!'
      redirect_to @blat
    else
      # Using flash.now[] because we want it to appear on *this* request
      flash.now[:errors] = @blat.errors.full_messages
      render :new
    end
  end

  def edit
  end

  def update
    @blat.assign_attributes(blat_params)

    if @blat.save
      flash[:notice] = 'Updated the blat!'
      redirect_to @blat
    else
      flash.now[:errors] = @blat.errors.full_messages
      render :edit
    end
  end

  def destroy
    if @blat.destroy
      flash[:notice] = 'Deleted the blat!'
      redirect_to action: :index
    else
      # Assume whatever prevented the destroy added an error message for us
      flash[:errors] = @blat.errors.full_messages
      redirect_to :back
    end
  end

  private

  def find_blat
    @blat = Blat.find(params[:id])
  end

  def blat_params
    params.require(:blat).permit(:title, :body)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/blats/_form.html.erb
<%= form_for @blat do |form| %>
  <div>
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>
  <div>
    <%= form.label :body %>
    <%= form.text_area :body, rows: 10, cols: 80 %>
  </div>
  <%= form.submit %>
<% end %>

app/views/blats/edit.html.erb
<%= render 'form' %>

app/views/blats/index.html.erb
<p><%= link_to 'New blat', new_blat_path %></p>

<dl>
  <% @blats.each do |blat| %>
    <dt><%= link_to blat.title, blat %></dt>
    <dd><%= truncate(blat.body, length: 100) %></dd>
  <% end %>
</dl>

<% if params[:show_all].blank? %>
  <p>
    Showing blats from the last 7 days.
    <%= link_to 'Show all blats?', blats_path(show_all: true) %>
  </p>
<% end %>

app/views/blats/new.html.erb
<%= form_for @blat do |form| %>
  <div>
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>
  <div>
    <%= form.label :body %>
    <%= form.text_area :body, rows: 10, cols: 80 %>
  </div>
  <%= form.submit %>
<% end %>

app/views/blats/show.html.erb
<p>
  <%= link_to 'Edit blat', edit_blat_path(@blat) %> |
  <%= link_to 'Delete blat', blat_path(@blat), method: :delete, confirm: 'Seriously?' %>
</p>
<h2><%= @blat.title %></h2>
<p><%= @blat.body %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blatter</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<h1><%= link_to 'Blatter', root_path %></h1>
<% if flash[:notice].present? %>
  <p><%= flash[:notice] %></p>
<% end %>
<% if flash[:errors].present? %>
  <p>Error: <%= flash[:errors].join(', ') %></p>
<% end %>

<%= yield %>

</body>
</html>